# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: cluster-api-provider-kind
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: ./bin/manager
    main: ./main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
      - -extldflags "-static"
archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  draft: false
  github:
    owner: mbovo
    name: cluster-api-provider-kind
  extra_files:
    - glob: ./metadata.yaml
    - glob: ./templates/cluster-template-kind.yaml
    - glob: ./templates/infrastructure-components.yaml
# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
