# permissions for end users to edit kindclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kindcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-kind
    app.kubernetes.io/part-of: cluster-api-provider-kind
    app.kubernetes.io/managed-by: kustomize
  name: kindcluster-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kindclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kindclusters/status
  verbs:
  - get
