name: Sanity Checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  verify:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.19'
    - uses: pre-commit/action@v3.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs:
      - verify
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: Setup Taskfile
        uses: arduino/setup-task@v1
      - name: "Integration tests"
        run: make test
  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Taskfile
        uses: arduino/setup-task@v1
      - name: "Build"
        run: task docker:build
