name: "Tag and build"
on:
  push:
    branches: ["main"]
    tags: ["*"]

permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.19'
    - uses: pre-commit/action@v3.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  tagging:
    name: "Tagging"
    runs-on: ubuntu-latest
    needs:
      - verify
    outputs:
      next_tag: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo Calculated Next Tag is ${{ steps.tag_version.outputs.new_tag }}

  docker-build:
    name: "Build docker image"
    runs-on: ubuntu-latest
    needs:
      - verify
      - tagging
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - run: echo ${{env.IMAGE_NAME}}:${{needs.tagging.outputs.next_tag}}

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{env.IMAGE_NAME}}
      #     flavor: |
      #       latest=auto
      #       prefix=
      #       suffix=
      #     tags: |
      #       type=raw,value=${{needs.tagging.outputs.next_tag}}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: Dockerfile
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      - name: Create infrastructure-components.yaml
        run: |
          make kustomize
          pushd config/docker-manager/ && \
          ../../bin/kustomize edit set image docker.io/jackbit/cluster-api-provider-kind=:${{ github.ref_name }} && \
          popd
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
