name: "Tag and build"
on:
  push:
    branches: ["main"]
    tags: ["*"]
jobs:
  tagging:
    name: "Tagging"
    needs: pre-commit
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo Calculated Next Tag is ${{ steps.tag_version.outputs.new_tag }}

  docker-build:
    name: "Build docker image"
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - tagging
    env:
      IMAGE_NAME: "jackbit/capi-provider-kind"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo ${{env.IMAGE_NAME}}:${{needs.tagging.outputs.next_tag}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.IMAGE_NAME}}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=raw,value=${{needs.tagging.outputs.next_tag}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
