name: "Kind Hack"
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write

jobs:
  image-build:
    name: "Build docker image"
    env:
      IMAGE_NAME: "docker.io/jackbit/kind-hack"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.IMAGE_NAME}}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./hack/kind-hack.Dockerfile
          context: ./hack
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
